name: Test Homebrew Formula

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit Formula
        run: brew audit --type=formula ./Formula/sandb0x-xtract0r.rb || true

      - name: Test Local Tap and Install
        run: |
          mkdir -p $(brew --repo)/Library/Taps/darnellwashingtonjr94/homebrew-xtractor
          cp -r . $(brew --repo)/Library/Taps/darnellwashingtonjr94/homebrew-xtractor
          brew install darnellwashingtonjr94/xtractor/sandb0x-xtract0r
