name: Test Homebrew Formula

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit Formula
        run: brew audit --type=formula ./Formula/sandb0x-xtract0r.rb || true

      - name: Test Local Tap and Install
        run: |
          brew tap --force darnellwashingtonjr94-art/xtractor .
          brew trust --formula darnellwashingtonjr94-art/xtractor/sandb0x-xtract0r
          brew install sandb0x-xtract0r
